<h1>Tutorial - Configuration</h1>

<?php include MODULES_ROOT.'tutorial/toc.php';?>
<p>Staple uses a global configuration file called <span class="code">application.ini</span>. 
The <span class="code">application.ini</span> file holds many settings that change how the 
application connects to a database, whether to use headers and footers, or how authentication
will take place. You can use the sample file below to get started. You will of course have to
customize it to fit your needs. Keep reading for a description on each setting.</p>

<h3>Sample Config</h3>
<pre>
[application]
<b>public_location</b> = <em>'/staple/public/'</em>

[page]
<b>header</b> = <i>MODULES_ROOT</i><em>'header.php'</em>
<b>footer</b> = <i>MODULES_ROOT</i><em>'footer.php'</em>

[db]
<b>autoconnect</b> = 0 <u>;Not yet implemented</u>
<b>host</b> = <em>'localhost'</em>
<b>username</b> = <em>'username'</em>
<b>password</b> = <em>'password'</em>
<b>db</b> = <em>'databasename'</em>

[auth]
<b>enabled</b> = 1
<b>adapter</b> = <em>'Staple_DBAuthAdapter'</em>
<b>controller</b> = <em>'accountController'</em>
<b>authtable</b> = <em>'accounts'</em>
<b>uidfield</b> = <em>'username'</em>
<b>pwfield</b> = <em>'password'</em>
<b>rolefield</b> = <em>'accountType'</em>
<b>pwenctype</b> = <em>'SHA1'</em>
<b>allowedRoute[]</b> = <em>'index/splash'</em> <u>;Not yet implemented</u>

[email]
<b>html</b> = 1
<b>from</b> = <em>'no-reply@staplecode.org'</em>
<b>bcc</b> = <em>''</em>
<b>server</b> = <em>''</em>
<b>template</b> = <i>MODULES_ROOT</i><em>'email/template.html'</em>

[errors]
<b>devmode</b> = 0
</pre>

<h3>Application Config</h3>

<h3>Page Config</h3>
<h3>Database Config</h3>
<h3>Authentication Config</h3>
<h3>Email Config</h3>
<h3>Errors Config</h3>
<p>Only one configurable option exists within the [errors] section of the application.ini file.
The <span class="code"><b>devmode</b> = 0</span> line allows you to enable or disable the code 
trace on Staple error pages. <b>This setting should be off (0) for production servers.</b> 
To turn on the code trace, change this value to 1.</p>  