<p>Welcome to Staple Code.</p>
<p>STAPLE is a PHP 5.3 framework designed to be simple to use and quick to develop on.
STAPLE is an implementation of the Model-View-Controller design pattern, with a few twists.</p>

<p>STAPLE does take advantage of some PHP 5.3 exclusive features. Your server will need to 
be running PHP 5.3 in order to support STAPLE.</p>

<p>STAPLE is licensed under the GNU Lesser General Public License.</p>
<br><br>
<p align="center">
<script type="text/javascript"><!--
google_ad_client = "ca-pub-6247159608336732";
/* Homepage Ads */
google_ad_slot = "3018639239";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
</p>