<h1>Download STAPLE</h1>

<p>STAPLE v0.7.6 (4-30-2012) <a href="<?php echo $this->link('download/download',array('v'=>'0.7.6')); ?>">Download Now</a> (1,226k)</p>
<p>STAPLE v0.5.9 (No Documentation) <a href="<?php echo $this->link('download/download',array('v'=>'0.5.9')); ?>">Download Now</a> (85k)</p>
<p>STAPLE v0.5.1 <a href="<?php echo $this->link('download/download',array('v'=>'0.5.1')); ?>">Download Now</a> (289k)</p>

<h3>Syste Requirements</h3>

<ul>
<li>Windows or Linux environment</li>
<li>PHP 5.3+</li>
<li>MySQL (Optional)</li>
</ul>