<?php echo $this->doctype; ?>
<html>
	<head>
		<title><?php echo $this->title; ?></title>
		<?php $this->styles(); ?>
		<?php $this->scripts();	?>
	</head>
	<body>
		<div id="main">
			<div id="title">
				<a href="<?php echo $this->link(array('index','index'));?>"><img src="<?php echo $this->link('images/logo.png');?>" alt="Staple Code"></a>
			</div>
			<div id="mainlinks">
				<ul>
					<li><a href="<?php echo $this->link(array('index','index'));?>">Home</a></li> |
					<li><a href="<?php echo $this->link(array('tutorial','index'));?>">Tutorial</a></li> |
					<li><a href="<?php echo $this->link(array('index','documentation'));?>">Documentation</a></li> |
					<li><a href="<?php echo $this->link(array('download','index'));?>">Download</a></li> |
					<li><a href="<?php echo $this->link(array('index','license'));?>">License</a></li> |
					<li><a href="<?php echo $this->link(array('index','about'));?>">About</a></li>
				</ul>
			</div>
			<div id="body">
				<?php $this->content();?>
			</div>
		</div> 
		<div id="footer">
			<ul>
				<li><a href="">Home</a></li> |
				<li><a href="<?php echo $this->link(array('tutorial','index'));?>">Tutorial</a></li> |
				<li><a href="">Documentation</a></li> |
				<li><a href="">Download</a></li> |
				<li><a href="">About</a></li>
			</ul>
		</div>
	</body>
</html>